service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10

functions:
  create:
    handler: handlers/create.handler
    events:
      - http:
          method: post
          path: create
    
  
  read:
    handler: handlers/read.handler
    events:
      - http:
          method: get
          path: read

  
  update:
    handler: handlers/update.handler
    events:
      - http:
          method: post
          path: update
  
  delete:
    handler: handlers/delete.handler
    events:
      - http:
          method: post
          path: delete

  


# you can add CloudFormation resource templates here
resources:
 Resources:
  SensorDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sensor-data-table
        AttributeDefinitions:
          - {AttributeName: type, AttributeType: S}
        KeySchema:
          - {AttributeName: type, KeyType: HASH}
        BillingMode: PAY_PER_REQUEST