service:
  name: mysense-tech-test

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs10.x
  environment:
    SECRET_NAME: ${env:SECRET_NAME, file(env.yml):SECRET_NAME}
    TABLE_NAME: ${env:TABLE_NAME, file(env.yml):TABLE_NAME}

functions:
  auth:
    handler: dist/handlers/auth.handler
    iamRoleStatementsName: ${self:service}-auth
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'ssm:GetParameter'
        Resource:
          Fn::Join:
            - ''
            - - 'arn:aws:ssm:eu-west-1:'
              - Ref: AWS::AccountId
              - ':parameter/${env:SECRET_NAME, file(env.yml):SECRET_NAME}'

  create:
    handler: dist/handlers/create.handler
    events:
      - http:
          method: post
          path: create
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    iamRoleStatementsName: ${self:service}-create
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          Fn::Join:
            - ':'
            - - 'arn:aws:dynamodb:eu-west-1'
              - Ref: AWS::AccountId
              - 'table/sensor-data-table'
    
  
  fetch:
    handler: dist/handlers/fetch.handler
    events:
      - http:
          method: get
          path: read/{id}
          request:
            parameters:
              paths:
                id: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    iamRoleStatementsName: ${self:service}-fetch
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
        Resource:
          Fn::Join:
            - ':'
            - - 'arn:aws:dynamodb:eu-west-1'
              - Ref: AWS::AccountId
              - 'table/sensor-data-table'
  
  list:
    handler: dist/handlers/list.handler
    events:
      - http:
          method: get
          path: read
          request:
            parameters:
              paths:
                id: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    iamRoleStatementsName: ${self:service}-list
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Scan
        Resource:
          Fn::Join:
            - ':'
            - - 'arn:aws:dynamodb:eu-west-1'
              - Ref: AWS::AccountId
              - 'table/sensor-data-table'

  
  update:
    handler: dist/handlers/update.handler
    events:
      - http:
          method: put
          path: update
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    iamRoleStatementsName: ${self:service}-update
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          Fn::Join:
            - ':'
            - - 'arn:aws:dynamodb:eu-west-1'
              - Ref: AWS::AccountId
              - 'table/sensor-data-table'
  
  delete:
    handler: dist/handlers/delete.handler
    events:
      - http:
          method: delete
          path: delete/{id}
          request:
            parameters:
              paths:
                id: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    iamRoleStatementsName: ${self:service}-delete
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource:
          Fn::Join:
            - ':'
            - - 'arn:aws:dynamodb:eu-west-1'
              - Ref: AWS::AccountId
              - 'table/sensor-data-table'


resources:
 Resources:
  SensorDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - {AttributeName: id, AttributeType: S}
        KeySchema:
          - {AttributeName: id, KeyType: HASH}
        BillingMode: PAY_PER_REQUEST